#.gitlab-ci.yml
image: vadivelk/alpine-sbt

# Defining our custom stages
stages:
 - build
 - test
 - release

compile-job:
  stage: build
  script:
    - sbt compile

test-job:
  stage: test
  script:
    - sbt test

release-job:
  stage: release
  script:
    - sbt assembly
  artifacts:
    paths:
      - target/scala-2.11/*.jar
  only:
    - master
    - tags
